import './globals.css';
import type { Metadata } from 'next';
import BaseLayout from './base';
// import { Provider } from 'react-redux';
// import { store } from '@/utils/redux/store';
// import Navigation from '@/components/navigation';
// import { UserInfo } from '@/types/interface';
// import { useState, useEffect } from 'react';
// import Auth from '@/lib/sdk/Authentication';
// import Link from 'next/link';
// import { Popover, Transition } from '@headlessui/react';
// import { Fragment } from 'react';
// import { MdKeyboardArrowUp, MdKeyboardArrowDown } from 'react-icons/md';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <BaseLayout>{children}</BaseLayout>;
}
